### PR TITLE
Missing unResponse caused JSON parsing error

### LINKED ISSUE #4: Getting single ssh key fails
The endpoint for `getSSHKey` fails, whereas `getSSHKeys` does not.

For testing in repl:

```haskell
:set -XOverloadedStrings
:set -XLambdaCase

import Control.Monad.Except
import Control.Monad.Reader

client = Client "<your_api_key>"

runDO' :: DO a -> IO a; runDO' action = runExceptT ((runReaderT $ runDO action) client) >>= \case Left err -> error (show err); Right result -> pure result

runDO' $ getSSHKey (Right "<fingerprint_of_ssh_key>")
```

### PR DESCRIPTION
**Pull request by wildsebastian**
This fixes #4.

Is it necessary to commit the dist folder as well?

### CODE REVIEW

**Comment by yigitozkavci** [comment]
Hi @wildsebastian, thank you for your contribution!

I will review this soon (planning on doing it tomorrow).

**Comment by wildsebastian** [comment]
Cool! You are welcome! 🙂

**Comment by yigitozkavci** [comment]
Thanks @wildsebastian, I tested and it's working fine. We can remove `dist` folder all together, you don't need to do anything about it in this PR.

**Comment by yigitozkavci** [comment]
Thanks @wildsebastian, I tested and it's working fine. We can remove `dist` folder all together, you don't need to do anything about it in this PR.

**Comment by yigitozkavci** [comment]
Thanks @wildsebastian, I tested and it's working fine. We can remove `dist` folder all together, you don't need to do anything about it in this PR.

**Pull request merged**
